Provides a rudimentary typeahead
elanthia-online/illthorn pull request #258
Opened 2023-10-17 09:39 UTC by litch

With this you can do the following 
`> swap \r swap`

And the result is what you'd expect.  I think you could probably string too many commands together and get the server mad at you for doing too much typeahead, but since this is all typed from the command line, YMMV.

2023-10-19 00:40 UTC, litch commented
Any thoughts on this @ondreian ?

2023-10-19 00:44 UTC, ondreian commented
yeah, I don't have a problem with the idea, would be good to use a return early pattern though please

2023-11-02 13:09 UTC, ondreian requested changes
Please use a return-early pattern instead of `else if`

2023-11-02 13:09 UTC, ondreian commented on src/frontend/components/session/cli.ts
> +    }
```suggestion
    if (command[0] == ":") {
      return Illthorn.bus.dispatchEvent(IllthornEvent.SUBMIT_ILLTHORN_COMMAND, command)
    }
    if (command[0] == ";") {
      // This is going to Lich, so we'll not monkey with it
      return this.session.sendCommand(command)
    } 
    return command.split("\\r").forEach(c => {
        c = c.trim()
        this.session.sendCommand(c)
      })
```

2023-11-02 14:34 UTC, litch commented on src/frontend/components/session/cli.ts
> +    }
Thank you!  Yes I got a little busy and hadn't gotten to this

2023-11-02 14:48 UTC, ondreian approved these changes
lgtm

2023-11-02 14:48 UTC, merged